name: GCC Builds
on: [push]

jobs:
  build:
    strategy:
      matrix:
        cxx_standard: [17]
        build_type: ["Release", "Debug"]
        configuration: [
          {"UBUNTU_VERSION":"18.04", "TOOLCHAIN_VERSION":"7"},
          {"UBUNTU_VERSION":"18.04", "TOOLCHAIN_VERSION":"8"},

          {"UBUNTU_VERSION":"20.04", "TOOLCHAIN_VERSION":"7"},
          {"UBUNTU_VERSION":"20.04", "TOOLCHAIN_VERSION":"8"},
          {"UBUNTU_VERSION":"20.04", "TOOLCHAIN_VERSION":"9"},
          {"UBUNTU_VERSION":"20.04", "TOOLCHAIN_VERSION":"10"},

          {"UBUNTU_VERSION":"22.04", "TOOLCHAIN_VERSION":"9"},
          {"UBUNTU_VERSION":"22.04", "TOOLCHAIN_VERSION":"10"},
          {"UBUNTU_VERSION":"22.04", "TOOLCHAIN_VERSION":"11"},
          {"UBUNTU_VERSION":"22.04", "TOOLCHAIN_VERSION":"12"},
          {"UBUNTU_VERSION":"22.04", "TOOLCHAIN_VERSION":"13"}
        ]

    runs-on: ubuntu-latest
    container:
      image: ubuntu:${{matrix.configuration.UBUNTU_VERSION}}

    steps:
      - uses: actions/checkout@v2

      - name: Install system dependencies
        env:
          DEBIAN_FRONTEND: noninteractive
        run: |
          apt update && apt-get install -y \
            software-properties-common ca-certificates \
            ninja-build make \
            zlib1g-dev wget

          add-apt-repository ppa:ubuntu-toolchain-r/test

          bash ./build/gcc/pyinstall.sh $(cat /etc/os-release | grep -a UBUNTU_CODENAME | sed -e 's/UBUNTU_CODENAME=//g')

          python3 -m pip install --upgrade pip
          python3 -m pip install --no-cache-dir conan==1.59 cmake

      - name: Install compiler
        run: |
          apt update && apt-get install -y gcc-${{matrix.configuration.TOOLCHAIN_VERSION}} g++-${{matrix.configuration.TOOLCHAIN_VERSION}}
          update-alternatives \
            --install /usr/bin/gcc gcc /usr/bin/gcc-${{matrix.configuration.TOOLCHAIN_VERSION}} 90 \
            --slave /usr/bin/g++ g++ /usr/bin/g++-${{matrix.configuration.TOOLCHAIN_VERSION}} \
            --slave /usr/bin/gcov gcov /usr/bin/gcov-${{matrix.configuration.TOOLCHAIN_VERSION}}

          update-alternatives --config gcc

      - name: Configure CMake
        env:
          CC: gcc-${{matrix.configuration.TOOLCHAIN_VERSION}}
          CXX: g++-${{matrix.configuration.TOOLCHAIN_VERSION}}
          BUILD_TYPE: ${{matrix.build_type}}
          CXX_STANDARD: ${{matrix.cxx_standard}}
        run: |
          mkdir -p local_build
          cmake -B local_build -GNinja \
            -DCMAKE_BUILD_TYPE=${BUILD_TYPE} \
            -DCMAKE_CXX_STANDARD=${CXX_STANDARD} \
            -DCMAKE_C_COMPILER=${CC} \
            -DCMAKE_CXX_COMPILER=${CXX}

      - name: Build
        run: cmake --build local_build

      - name: Test
        working-directory: local_build
        run: ctest --rerun-failed --output-on-failure
